export const GET_ALL_USER_REQUEST="GET_ALL_USER_REQUEST";
export const GET_ALL_USER_ERROR="GET_ALL_USER_ERROR";
export const ADD_USER= "ADD_USER";
export const GET_ALL_USER="GET_ALL_USER";
export const GET_SINGLE_USER="GET_SINGLE_USER";
export const DELETE_USER="DELETE_USER";
export const UPDATE_USER="UPDATE_USER";